### ISSUE TITLE
Add CLI for goodreadsquote.py 

### ISSUE THREAD

**Issue by abhinuvpitale** [abhinuvpitale/Spiders#3]
Add argparser to select topic and number of pages to parse

**Comment by tanaytoshniwal** [comment]
I would like to work on this

**Comment by abhinuvpitale** [comment]
go ahead!

**Comment by tanaytoshniwal** [comment]
refer to this PR: https://github.com/abhinuvpitale/Spiders/pull/5 @abhinuvpitale
